# Generated by Django 4.1.4 on 2023-01-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nickname", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nickname",
            name="player_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Player Adjustment",
            ),
        ),
        migrations.AddField(
            model_name="nickname",
            name="player_rb",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Player Rakeback",
            ),
        ),
        migrations.AlterField(
            model_name="nickname",
            name="player",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nickname2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
