# Generated by Django 4.1.4 on 2023-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nickname", "0002_nickname_player_adjustment_nickname_player_rb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nickname",
            name="player_rb",
            field=models.DecimalField(
                decimal_places=3,
                default=0.0,
                max_digits=10,
                verbose_name="Player Rakeback",
            ),
        ),
    ]
