# Generated by Django 4.1.4 on 2023-02-04 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nickname", "0003_alter_nickname_player_rb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nickname",
            name="player",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nickname2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
