# Generated by Django 4.1.4 on 2023-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club", models.CharField(max_length=100, verbose_name="Club")),
                ("nickname", models.CharField(max_length=100, verbose_name="Nickname")),
                ("agents", models.CharField(max_length=100, verbose_name="Agent")),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=50,
                        default=0.0,
                        max_digits=100,
                        verbose_name="PROFIT/LOSS",
                    ),
                ),
                (
                    "rake",
                    models.DecimalField(
                        decimal_places=50,
                        default=0.0,
                        max_digits=100,
                        verbose_name="Rake",
                    ),
                ),
                (
                    "deal",
                    models.DecimalField(
                        decimal_places=5,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Affiliate Deal",
                    ),
                ),
                (
                    "rakeback",
                    models.DecimalField(
                        decimal_places=50,
                        default=0.0,
                        max_digits=100,
                        verbose_name="Affiliate Rakeback",
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(
                        decimal_places=50,
                        default=0.0,
                        max_digits=100,
                        verbose_name="Affiliate Adjustment",
                    ),
                ),
                (
                    "agent_settlement",
                    models.DecimalField(
                        decimal_places=50,
                        default=0.0,
                        max_digits=100,
                        verbose_name="Agent Settlement",
                    ),
                ),
                (
                    "date",
                    models.CharField(max_length=50, verbose_name="Date: mon-sund"),
                ),
            ],
        ),
    ]
