# Generated by Django 4.1.4 on 2023-02-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nickname", "0004_alter_nickname_player"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="club",
            field=models.CharField(
                blank=True,
                help_text="optional",
                max_length=100,
                null=True,
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("PLN", "PLN"),
                    ("BRL", "BRL"),
                    ("ILS", "ILS"),
                ],
                default="USD",
                help_text="orginal currency",
                max_length=50,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="date",
            field=models.CharField(
                default="dd/mm/yy",
                help_text="transaction date dd/mm/yy",
                max_length=100,
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settlement",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="optional",
                max_length=1000,
                null=True,
                verbose_name="Club",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="exchangeRate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="exchange rate to the USD, leave 1.00 if orginal value in USD",
                max_digits=14,
                verbose_name="Transaction in USD",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="transactionUSD",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="transaction in USD",
                max_digits=14,
                verbose_name="Transaction in USD",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="transactionValue",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="transaction value (original currency)",
                max_digits=14,
                verbose_name="Transaction Value",
            ),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="nickname",
            field=models.ForeignKey(
                blank=True,
                help_text="optional",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nickname.nickname",
                verbose_name="nickname",
            ),
        ),
    ]
